// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle133 = {  abCircleGetBounds, abCircleCheck, chordVec133, 133};
