// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle139 = {  abCircleGetBounds, abCircleCheck, chordVec139, 139};
