// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle129 = {  abCircleGetBounds, abCircleCheck, chordVec129, 129};
