// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle122 = {  abCircleGetBounds, abCircleCheck, chordVec122, 122};
