// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle108 = {  abCircleGetBounds, abCircleCheck, chordVec108, 108};
