// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle127 = {  abCircleGetBounds, abCircleCheck, chordVec127, 127};
