// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle132 = {  abCircleGetBounds, abCircleCheck, chordVec132, 132};
