// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle143 = {  abCircleGetBounds, abCircleCheck, chordVec143, 143};
