// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle100 = {  abCircleGetBounds, abCircleCheck, chordVec100, 100};
