// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle147 = {  abCircleGetBounds, abCircleCheck, chordVec147, 147};
