// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle144 = {  abCircleGetBounds, abCircleCheck, chordVec144, 144};
