// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle146 = {  abCircleGetBounds, abCircleCheck, chordVec146, 146};
