// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle113 = {  abCircleGetBounds, abCircleCheck, chordVec113, 113};
