// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle138 = {  abCircleGetBounds, abCircleCheck, chordVec138, 138};
