// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle104 = {  abCircleGetBounds, abCircleCheck, chordVec104, 104};
