// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle110 = {  abCircleGetBounds, abCircleCheck, chordVec110, 110};
