// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle101 = {  abCircleGetBounds, abCircleCheck, chordVec101, 101};
