// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle102 = {  abCircleGetBounds, abCircleCheck, chordVec102, 102};
