// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle103 = {  abCircleGetBounds, abCircleCheck, chordVec103, 103};
