// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle111 = {  abCircleGetBounds, abCircleCheck, chordVec111, 111};
