// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle141 = {  abCircleGetBounds, abCircleCheck, chordVec141, 141};
