// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle149 = {  abCircleGetBounds, abCircleCheck, chordVec149, 149};
