// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle118 = {  abCircleGetBounds, abCircleCheck, chordVec118, 118};
