// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle114 = {  abCircleGetBounds, abCircleCheck, chordVec114, 114};
