// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle120 = {  abCircleGetBounds, abCircleCheck, chordVec120, 120};
