// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle128 = {  abCircleGetBounds, abCircleCheck, chordVec128, 128};
