// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle105 = {  abCircleGetBounds, abCircleCheck, chordVec105, 105};
