// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle135 = {  abCircleGetBounds, abCircleCheck, chordVec135, 135};
