// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle148 = {  abCircleGetBounds, abCircleCheck, chordVec148, 148};
