// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle116 = {  abCircleGetBounds, abCircleCheck, chordVec116, 116};
