// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle150 = {  abCircleGetBounds, abCircleCheck, chordVec150, 150};
