// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle142 = {  abCircleGetBounds, abCircleCheck, chordVec142, 142};
