// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle117 = {  abCircleGetBounds, abCircleCheck, chordVec117, 117};
