// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle125 = {  abCircleGetBounds, abCircleCheck, chordVec125, 125};
