// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle109 = {  abCircleGetBounds, abCircleCheck, chordVec109, 109};
