// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle134 = {  abCircleGetBounds, abCircleCheck, chordVec134, 134};
