// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle124 = {  abCircleGetBounds, abCircleCheck, chordVec124, 124};
