// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle145 = {  abCircleGetBounds, abCircleCheck, chordVec145, 145};
