// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle137 = {  abCircleGetBounds, abCircleCheck, chordVec137, 137};
