// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle136 = {  abCircleGetBounds, abCircleCheck, chordVec136, 136};
