// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle119 = {  abCircleGetBounds, abCircleCheck, chordVec119, 119};
