// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle126 = {  abCircleGetBounds, abCircleCheck, chordVec126, 126};
