// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle115 = {  abCircleGetBounds, abCircleCheck, chordVec115, 115};
