// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle140 = {  abCircleGetBounds, abCircleCheck, chordVec140, 140};
