// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle130 = {  abCircleGetBounds, abCircleCheck, chordVec130, 130};
