// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle121 = {  abCircleGetBounds, abCircleCheck, chordVec121, 121};
