// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle112 = {  abCircleGetBounds, abCircleCheck, chordVec112, 112};
