// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle107 = {  abCircleGetBounds, abCircleCheck, chordVec107, 107};
