// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "abCircle.h"

#include "chordVec.h"

const AbCircle circle106 = {  abCircleGetBounds, abCircleCheck, chordVec106, 106};
