// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec51[52] = {
    51, // dist along axis = 0
    51, // dist along axis = 1
    51, // dist along axis = 2
    51, // dist along axis = 3
    51, // dist along axis = 4
    51, // dist along axis = 5
    51, // dist along axis = 6
    51, // dist along axis = 7
    50, // dist along axis = 8
    50, // dist along axis = 9
    50, // dist along axis = 10
    50, // dist along axis = 11
    50, // dist along axis = 12
    49, // dist along axis = 13
    49, // dist along axis = 14
    49, // dist along axis = 15
    48, // dist along axis = 16
    48, // dist along axis = 17
    48, // dist along axis = 18
    47, // dist along axis = 19
    47, // dist along axis = 20
    46, // dist along axis = 21
    46, // dist along axis = 22
    46, // dist along axis = 23
    45, // dist along axis = 24
    44, // dist along axis = 25
    44, // dist along axis = 26
    43, // dist along axis = 27
    43, // dist along axis = 28
    42, // dist along axis = 29
    41, // dist along axis = 30
    40, // dist along axis = 31
    40, // dist along axis = 32
    39, // dist along axis = 33
    38, // dist along axis = 34
    37, // dist along axis = 35
    36, // dist along axis = 36
    35, // dist along axis = 37
    34, // dist along axis = 38
    33, // dist along axis = 39
    31, // dist along axis = 40
    30, // dist along axis = 41
    29, // dist along axis = 42
    27, // dist along axis = 43
    25, // dist along axis = 44
    24, // dist along axis = 45
    21, // dist along axis = 46
    19, // dist along axis = 47
    16, // dist along axis = 48
    13, // dist along axis = 49
    8, // dist along axis = 50
    0, // dist along axis = 51
};

