// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec39[40] = {
    39, // dist along axis = 0
    39, // dist along axis = 1
    39, // dist along axis = 2
    39, // dist along axis = 3
    39, // dist along axis = 4
    39, // dist along axis = 5
    39, // dist along axis = 6
    38, // dist along axis = 7
    38, // dist along axis = 8
    38, // dist along axis = 9
    38, // dist along axis = 10
    37, // dist along axis = 11
    37, // dist along axis = 12
    37, // dist along axis = 13
    36, // dist along axis = 14
    36, // dist along axis = 15
    36, // dist along axis = 16
    35, // dist along axis = 17
    35, // dist along axis = 18
    34, // dist along axis = 19
    33, // dist along axis = 20
    33, // dist along axis = 21
    32, // dist along axis = 22
    31, // dist along axis = 23
    31, // dist along axis = 24
    30, // dist along axis = 25
    29, // dist along axis = 26
    28, // dist along axis = 27
    27, // dist along axis = 28
    26, // dist along axis = 29
    25, // dist along axis = 30
    23, // dist along axis = 31
    22, // dist along axis = 32
    20, // dist along axis = 33
    19, // dist along axis = 34
    17, // dist along axis = 35
    14, // dist along axis = 36
    11, // dist along axis = 37
    7, // dist along axis = 38
    0, // dist along axis = 39
};

