// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec3[4] = {
    3, // dist along axis = 0
    3, // dist along axis = 1
    2, // dist along axis = 2
    0, // dist along axis = 3
};

