// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec43[44] = {
    43, // dist along axis = 0
    43, // dist along axis = 1
    43, // dist along axis = 2
    43, // dist along axis = 3
    43, // dist along axis = 4
    43, // dist along axis = 5
    43, // dist along axis = 6
    42, // dist along axis = 7
    42, // dist along axis = 8
    42, // dist along axis = 9
    42, // dist along axis = 10
    42, // dist along axis = 11
    41, // dist along axis = 12
    41, // dist along axis = 13
    41, // dist along axis = 14
    40, // dist along axis = 15
    40, // dist along axis = 16
    39, // dist along axis = 17
    39, // dist along axis = 18
    39, // dist along axis = 19
    38, // dist along axis = 20
    38, // dist along axis = 21
    37, // dist along axis = 22
    36, // dist along axis = 23
    36, // dist along axis = 24
    35, // dist along axis = 25
    34, // dist along axis = 26
    33, // dist along axis = 27
    33, // dist along axis = 28
    32, // dist along axis = 29
    31, // dist along axis = 30
    30, // dist along axis = 31
    29, // dist along axis = 32
    27, // dist along axis = 33
    26, // dist along axis = 34
    25, // dist along axis = 35
    23, // dist along axis = 36
    22, // dist along axis = 37
    20, // dist along axis = 38
    17, // dist along axis = 39
    15, // dist along axis = 40
    12, // dist along axis = 41
    7, // dist along axis = 42
    0, // dist along axis = 43
};

