// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec14[15] = {
    14, // dist along axis = 0
    14, // dist along axis = 1
    14, // dist along axis = 2
    14, // dist along axis = 3
    13, // dist along axis = 4
    13, // dist along axis = 5
    13, // dist along axis = 6
    12, // dist along axis = 7
    11, // dist along axis = 8
    11, // dist along axis = 9
    10, // dist along axis = 10
    8, // dist along axis = 11
    7, // dist along axis = 12
    4, // dist along axis = 13
    0, // dist along axis = 14
};

