// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec18[19] = {
    18, // dist along axis = 0
    18, // dist along axis = 1
    18, // dist along axis = 2
    18, // dist along axis = 3
    18, // dist along axis = 4
    17, // dist along axis = 5
    17, // dist along axis = 6
    17, // dist along axis = 7
    16, // dist along axis = 8
    16, // dist along axis = 9
    15, // dist along axis = 10
    14, // dist along axis = 11
    13, // dist along axis = 12
    12, // dist along axis = 13
    11, // dist along axis = 14
    10, // dist along axis = 15
    8, // dist along axis = 16
    5, // dist along axis = 17
    0, // dist along axis = 18
};

