// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec42[43] = {
    42, // dist along axis = 0
    42, // dist along axis = 1
    42, // dist along axis = 2
    42, // dist along axis = 3
    42, // dist along axis = 4
    42, // dist along axis = 5
    42, // dist along axis = 6
    41, // dist along axis = 7
    41, // dist along axis = 8
    41, // dist along axis = 9
    41, // dist along axis = 10
    41, // dist along axis = 11
    40, // dist along axis = 12
    40, // dist along axis = 13
    40, // dist along axis = 14
    39, // dist along axis = 15
    39, // dist along axis = 16
    38, // dist along axis = 17
    38, // dist along axis = 18
    37, // dist along axis = 19
    37, // dist along axis = 20
    36, // dist along axis = 21
    36, // dist along axis = 22
    35, // dist along axis = 23
    34, // dist along axis = 24
    34, // dist along axis = 25
    33, // dist along axis = 26
    32, // dist along axis = 27
    31, // dist along axis = 28
    30, // dist along axis = 29
    29, // dist along axis = 30
    28, // dist along axis = 31
    27, // dist along axis = 32
    26, // dist along axis = 33
    24, // dist along axis = 34
    23, // dist along axis = 35
    21, // dist along axis = 36
    19, // dist along axis = 37
    17, // dist along axis = 38
    15, // dist along axis = 39
    12, // dist along axis = 40
    7, // dist along axis = 41
    0, // dist along axis = 42
};

