// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec2[3] = {
    2, // dist along axis = 0
    2, // dist along axis = 1
    0, // dist along axis = 2
};

