// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec8[9] = {
    8, // dist along axis = 0
    8, // dist along axis = 1
    8, // dist along axis = 2
    7, // dist along axis = 3
    7, // dist along axis = 4
    6, // dist along axis = 5
    5, // dist along axis = 6
    3, // dist along axis = 7
    0, // dist along axis = 8
};

