// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec5[6] = {
    5, // dist along axis = 0
    5, // dist along axis = 1
    5, // dist along axis = 2
    4, // dist along axis = 3
    3, // dist along axis = 4
    0, // dist along axis = 5
};

