// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec11[12] = {
    11, // dist along axis = 0
    11, // dist along axis = 1
    11, // dist along axis = 2
    11, // dist along axis = 3
    10, // dist along axis = 4
    10, // dist along axis = 5
    9, // dist along axis = 6
    8, // dist along axis = 7
    8, // dist along axis = 8
    6, // dist along axis = 9
    4, // dist along axis = 10
    0, // dist along axis = 11
};

