// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec6[7] = {
    6, // dist along axis = 0
    6, // dist along axis = 1
    6, // dist along axis = 2
    5, // dist along axis = 3
    4, // dist along axis = 4
    3, // dist along axis = 5
    0, // dist along axis = 6
};

