// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec41[42] = {
    41, // dist along axis = 0
    41, // dist along axis = 1
    41, // dist along axis = 2
    41, // dist along axis = 3
    41, // dist along axis = 4
    41, // dist along axis = 5
    41, // dist along axis = 6
    40, // dist along axis = 7
    40, // dist along axis = 8
    40, // dist along axis = 9
    40, // dist along axis = 10
    39, // dist along axis = 11
    39, // dist along axis = 12
    39, // dist along axis = 13
    39, // dist along axis = 14
    38, // dist along axis = 15
    38, // dist along axis = 16
    37, // dist along axis = 17
    37, // dist along axis = 18
    36, // dist along axis = 19
    36, // dist along axis = 20
    35, // dist along axis = 21
    35, // dist along axis = 22
    34, // dist along axis = 23
    33, // dist along axis = 24
    32, // dist along axis = 25
    32, // dist along axis = 26
    31, // dist along axis = 27
    30, // dist along axis = 28
    29, // dist along axis = 29
    28, // dist along axis = 30
    27, // dist along axis = 31
    25, // dist along axis = 32
    24, // dist along axis = 33
    23, // dist along axis = 34
    21, // dist along axis = 35
    19, // dist along axis = 36
    17, // dist along axis = 37
    15, // dist along axis = 38
    11, // dist along axis = 39
    7, // dist along axis = 40
    0, // dist along axis = 41
};

