// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec4[5] = {
    4, // dist along axis = 0
    4, // dist along axis = 1
    3, // dist along axis = 2
    3, // dist along axis = 3
    0, // dist along axis = 4
};

