// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec9[10] = {
    9, // dist along axis = 0
    9, // dist along axis = 1
    9, // dist along axis = 2
    8, // dist along axis = 3
    8, // dist along axis = 4
    7, // dist along axis = 5
    7, // dist along axis = 6
    5, // dist along axis = 7
    3, // dist along axis = 8
    0, // dist along axis = 9
};

