// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec49[50] = {
    49, // dist along axis = 0
    49, // dist along axis = 1
    49, // dist along axis = 2
    49, // dist along axis = 3
    49, // dist along axis = 4
    49, // dist along axis = 5
    49, // dist along axis = 6
    48, // dist along axis = 7
    48, // dist along axis = 8
    48, // dist along axis = 9
    48, // dist along axis = 10
    48, // dist along axis = 11
    48, // dist along axis = 12
    47, // dist along axis = 13
    47, // dist along axis = 14
    47, // dist along axis = 15
    46, // dist along axis = 16
    46, // dist along axis = 17
    46, // dist along axis = 18
    45, // dist along axis = 19
    45, // dist along axis = 20
    44, // dist along axis = 21
    44, // dist along axis = 22
    43, // dist along axis = 23
    43, // dist along axis = 24
    42, // dist along axis = 25
    42, // dist along axis = 26
    41, // dist along axis = 27
    40, // dist along axis = 28
    39, // dist along axis = 29
    39, // dist along axis = 30
    38, // dist along axis = 31
    37, // dist along axis = 32
    36, // dist along axis = 33
    35, // dist along axis = 34
    34, // dist along axis = 35
    33, // dist along axis = 36
    32, // dist along axis = 37
    31, // dist along axis = 38
    29, // dist along axis = 39
    28, // dist along axis = 40
    27, // dist along axis = 41
    25, // dist along axis = 42
    23, // dist along axis = 43
    21, // dist along axis = 44
    19, // dist along axis = 45
    16, // dist along axis = 46
    13, // dist along axis = 47
    7, // dist along axis = 48
    0, // dist along axis = 49
};

