// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec17[18] = {
    17, // dist along axis = 0
    17, // dist along axis = 1
    17, // dist along axis = 2
    17, // dist along axis = 3
    17, // dist along axis = 4
    16, // dist along axis = 5
    16, // dist along axis = 6
    15, // dist along axis = 7
    15, // dist along axis = 8
    14, // dist along axis = 9
    14, // dist along axis = 10
    13, // dist along axis = 11
    12, // dist along axis = 12
    11, // dist along axis = 13
    9, // dist along axis = 14
    7, // dist along axis = 15
    5, // dist along axis = 16
    0, // dist along axis = 17
};

