// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec47[48] = {
    47, // dist along axis = 0
    47, // dist along axis = 1
    47, // dist along axis = 2
    47, // dist along axis = 3
    47, // dist along axis = 4
    47, // dist along axis = 5
    47, // dist along axis = 6
    46, // dist along axis = 7
    46, // dist along axis = 8
    46, // dist along axis = 9
    46, // dist along axis = 10
    46, // dist along axis = 11
    45, // dist along axis = 12
    45, // dist along axis = 13
    45, // dist along axis = 14
    45, // dist along axis = 15
    44, // dist along axis = 16
    44, // dist along axis = 17
    43, // dist along axis = 18
    43, // dist along axis = 19
    43, // dist along axis = 20
    42, // dist along axis = 21
    42, // dist along axis = 22
    41, // dist along axis = 23
    40, // dist along axis = 24
    40, // dist along axis = 25
    39, // dist along axis = 26
    38, // dist along axis = 27
    38, // dist along axis = 28
    37, // dist along axis = 29
    36, // dist along axis = 30
    35, // dist along axis = 31
    34, // dist along axis = 32
    33, // dist along axis = 33
    32, // dist along axis = 34
    31, // dist along axis = 35
    30, // dist along axis = 36
    29, // dist along axis = 37
    27, // dist along axis = 38
    26, // dist along axis = 39
    24, // dist along axis = 40
    23, // dist along axis = 41
    21, // dist along axis = 42
    18, // dist along axis = 43
    16, // dist along axis = 44
    12, // dist along axis = 45
    7, // dist along axis = 46
    0, // dist along axis = 47
};

