// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec21[22] = {
    21, // dist along axis = 0
    21, // dist along axis = 1
    21, // dist along axis = 2
    21, // dist along axis = 3
    21, // dist along axis = 4
    20, // dist along axis = 5
    20, // dist along axis = 6
    20, // dist along axis = 7
    19, // dist along axis = 8
    19, // dist along axis = 9
    18, // dist along axis = 10
    18, // dist along axis = 11
    17, // dist along axis = 12
    16, // dist along axis = 13
    16, // dist along axis = 14
    15, // dist along axis = 15
    13, // dist along axis = 16
    12, // dist along axis = 17
    10, // dist along axis = 18
    8, // dist along axis = 19
    5, // dist along axis = 20
    0, // dist along axis = 21
};

