// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec12[13] = {
    12, // dist along axis = 0
    12, // dist along axis = 1
    12, // dist along axis = 2
    12, // dist along axis = 3
    11, // dist along axis = 4
    11, // dist along axis = 5
    10, // dist along axis = 6
    10, // dist along axis = 7
    9, // dist along axis = 8
    8, // dist along axis = 9
    6, // dist along axis = 10
    4, // dist along axis = 11
    0, // dist along axis = 12
};

