// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec20[21] = {
    20, // dist along axis = 0
    20, // dist along axis = 1
    20, // dist along axis = 2
    20, // dist along axis = 3
    20, // dist along axis = 4
    19, // dist along axis = 5
    19, // dist along axis = 6
    19, // dist along axis = 7
    18, // dist along axis = 8
    18, // dist along axis = 9
    17, // dist along axis = 10
    17, // dist along axis = 11
    16, // dist along axis = 12
    15, // dist along axis = 13
    14, // dist along axis = 14
    13, // dist along axis = 15
    12, // dist along axis = 16
    10, // dist along axis = 17
    8, // dist along axis = 18
    5, // dist along axis = 19
    0, // dist along axis = 20
};

