// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec23[24] = {
    23, // dist along axis = 0
    23, // dist along axis = 1
    23, // dist along axis = 2
    23, // dist along axis = 3
    23, // dist along axis = 4
    22, // dist along axis = 5
    22, // dist along axis = 6
    22, // dist along axis = 7
    22, // dist along axis = 8
    21, // dist along axis = 9
    21, // dist along axis = 10
    20, // dist along axis = 11
    20, // dist along axis = 12
    19, // dist along axis = 13
    18, // dist along axis = 14
    17, // dist along axis = 15
    17, // dist along axis = 16
    15, // dist along axis = 17
    14, // dist along axis = 18
    13, // dist along axis = 19
    11, // dist along axis = 20
    9, // dist along axis = 21
    5, // dist along axis = 22
    0, // dist along axis = 23
};

