// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec22[23] = {
    22, // dist along axis = 0
    22, // dist along axis = 1
    22, // dist along axis = 2
    22, // dist along axis = 3
    22, // dist along axis = 4
    21, // dist along axis = 5
    21, // dist along axis = 6
    21, // dist along axis = 7
    20, // dist along axis = 8
    20, // dist along axis = 9
    20, // dist along axis = 10
    19, // dist along axis = 11
    18, // dist along axis = 12
    18, // dist along axis = 13
    17, // dist along axis = 14
    16, // dist along axis = 15
    15, // dist along axis = 16
    14, // dist along axis = 17
    12, // dist along axis = 18
    11, // dist along axis = 19
    8, // dist along axis = 20
    5, // dist along axis = 21
    0, // dist along axis = 22
};

