// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec19[20] = {
    19, // dist along axis = 0
    19, // dist along axis = 1
    19, // dist along axis = 2
    19, // dist along axis = 3
    19, // dist along axis = 4
    18, // dist along axis = 5
    18, // dist along axis = 6
    18, // dist along axis = 7
    17, // dist along axis = 8
    17, // dist along axis = 9
    16, // dist along axis = 10
    15, // dist along axis = 11
    15, // dist along axis = 12
    14, // dist along axis = 13
    13, // dist along axis = 14
    11, // dist along axis = 15
    10, // dist along axis = 16
    8, // dist along axis = 17
    5, // dist along axis = 18
    0, // dist along axis = 19
};

