// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec48[49] = {
    48, // dist along axis = 0
    48, // dist along axis = 1
    48, // dist along axis = 2
    48, // dist along axis = 3
    48, // dist along axis = 4
    48, // dist along axis = 5
    48, // dist along axis = 6
    47, // dist along axis = 7
    47, // dist along axis = 8
    47, // dist along axis = 9
    47, // dist along axis = 10
    47, // dist along axis = 11
    46, // dist along axis = 12
    46, // dist along axis = 13
    46, // dist along axis = 14
    46, // dist along axis = 15
    45, // dist along axis = 16
    45, // dist along axis = 17
    44, // dist along axis = 18
    44, // dist along axis = 19
    44, // dist along axis = 20
    43, // dist along axis = 21
    43, // dist along axis = 22
    42, // dist along axis = 23
    42, // dist along axis = 24
    41, // dist along axis = 25
    40, // dist along axis = 26
    40, // dist along axis = 27
    39, // dist along axis = 28
    38, // dist along axis = 29
    37, // dist along axis = 30
    37, // dist along axis = 31
    36, // dist along axis = 32
    35, // dist along axis = 33
    34, // dist along axis = 34
    33, // dist along axis = 35
    32, // dist along axis = 36
    30, // dist along axis = 37
    29, // dist along axis = 38
    28, // dist along axis = 39
    26, // dist along axis = 40
    25, // dist along axis = 41
    23, // dist along axis = 42
    21, // dist along axis = 43
    18, // dist along axis = 44
    16, // dist along axis = 45
    12, // dist along axis = 46
    7, // dist along axis = 47
    0, // dist along axis = 48
};

