// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec36[37] = {
    36, // dist along axis = 0
    36, // dist along axis = 1
    36, // dist along axis = 2
    36, // dist along axis = 3
    36, // dist along axis = 4
    36, // dist along axis = 5
    35, // dist along axis = 6
    35, // dist along axis = 7
    35, // dist along axis = 8
    35, // dist along axis = 9
    35, // dist along axis = 10
    34, // dist along axis = 11
    34, // dist along axis = 12
    34, // dist along axis = 13
    33, // dist along axis = 14
    33, // dist along axis = 15
    32, // dist along axis = 16
    32, // dist along axis = 17
    31, // dist along axis = 18
    31, // dist along axis = 19
    30, // dist along axis = 20
    29, // dist along axis = 21
    28, // dist along axis = 22
    28, // dist along axis = 23
    27, // dist along axis = 24
    26, // dist along axis = 25
    25, // dist along axis = 26
    24, // dist along axis = 27
    22, // dist along axis = 28
    21, // dist along axis = 29
    20, // dist along axis = 30
    18, // dist along axis = 31
    16, // dist along axis = 32
    14, // dist along axis = 33
    11, // dist along axis = 34
    6, // dist along axis = 35
    0, // dist along axis = 36
};

