// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec38[39] = {
    38, // dist along axis = 0
    38, // dist along axis = 1
    38, // dist along axis = 2
    38, // dist along axis = 3
    38, // dist along axis = 4
    38, // dist along axis = 5
    38, // dist along axis = 6
    37, // dist along axis = 7
    37, // dist along axis = 8
    37, // dist along axis = 9
    37, // dist along axis = 10
    36, // dist along axis = 11
    36, // dist along axis = 12
    36, // dist along axis = 13
    35, // dist along axis = 14
    35, // dist along axis = 15
    34, // dist along axis = 16
    34, // dist along axis = 17
    33, // dist along axis = 18
    33, // dist along axis = 19
    32, // dist along axis = 20
    32, // dist along axis = 21
    31, // dist along axis = 22
    30, // dist along axis = 23
    29, // dist along axis = 24
    29, // dist along axis = 25
    28, // dist along axis = 26
    27, // dist along axis = 27
    26, // dist along axis = 28
    24, // dist along axis = 29
    23, // dist along axis = 30
    22, // dist along axis = 31
    20, // dist along axis = 32
    18, // dist along axis = 33
    16, // dist along axis = 34
    14, // dist along axis = 35
    11, // dist along axis = 36
    7, // dist along axis = 37
    0, // dist along axis = 38
};

