// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec24[25] = {
    24, // dist along axis = 0
    24, // dist along axis = 1
    24, // dist along axis = 2
    24, // dist along axis = 3
    24, // dist along axis = 4
    23, // dist along axis = 5
    23, // dist along axis = 6
    23, // dist along axis = 7
    23, // dist along axis = 8
    22, // dist along axis = 9
    22, // dist along axis = 10
    21, // dist along axis = 11
    21, // dist along axis = 12
    20, // dist along axis = 13
    19, // dist along axis = 14
    19, // dist along axis = 15
    18, // dist along axis = 16
    17, // dist along axis = 17
    16, // dist along axis = 18
    14, // dist along axis = 19
    13, // dist along axis = 20
    11, // dist along axis = 21
    9, // dist along axis = 22
    5, // dist along axis = 23
    0, // dist along axis = 24
};

