// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec35[36] = {
    35, // dist along axis = 0
    35, // dist along axis = 1
    35, // dist along axis = 2
    35, // dist along axis = 3
    35, // dist along axis = 4
    35, // dist along axis = 5
    34, // dist along axis = 6
    34, // dist along axis = 7
    34, // dist along axis = 8
    34, // dist along axis = 9
    34, // dist along axis = 10
    33, // dist along axis = 11
    33, // dist along axis = 12
    32, // dist along axis = 13
    32, // dist along axis = 14
    32, // dist along axis = 15
    31, // dist along axis = 16
    31, // dist along axis = 17
    30, // dist along axis = 18
    29, // dist along axis = 19
    29, // dist along axis = 20
    28, // dist along axis = 21
    27, // dist along axis = 22
    26, // dist along axis = 23
    25, // dist along axis = 24
    24, // dist along axis = 25
    23, // dist along axis = 26
    22, // dist along axis = 27
    21, // dist along axis = 28
    19, // dist along axis = 29
    18, // dist along axis = 30
    16, // dist along axis = 31
    13, // dist along axis = 32
    11, // dist along axis = 33
    6, // dist along axis = 34
    0, // dist along axis = 35
};

