// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec15[16] = {
    15, // dist along axis = 0
    15, // dist along axis = 1
    15, // dist along axis = 2
    15, // dist along axis = 3
    14, // dist along axis = 4
    14, // dist along axis = 5
    14, // dist along axis = 6
    13, // dist along axis = 7
    13, // dist along axis = 8
    12, // dist along axis = 9
    11, // dist along axis = 10
    10, // dist along axis = 11
    9, // dist along axis = 12
    7, // dist along axis = 13
    4, // dist along axis = 14
    0, // dist along axis = 15
};

