// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec7[8] = {
    7, // dist along axis = 0
    7, // dist along axis = 1
    7, // dist along axis = 2
    6, // dist along axis = 3
    6, // dist along axis = 4
    5, // dist along axis = 5
    3, // dist along axis = 6
    0, // dist along axis = 7
};

