// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec31[32] = {
    31, // dist along axis = 0
    31, // dist along axis = 1
    31, // dist along axis = 2
    31, // dist along axis = 3
    31, // dist along axis = 4
    31, // dist along axis = 5
    30, // dist along axis = 6
    30, // dist along axis = 7
    30, // dist along axis = 8
    30, // dist along axis = 9
    29, // dist along axis = 10
    29, // dist along axis = 11
    29, // dist along axis = 12
    28, // dist along axis = 13
    28, // dist along axis = 14
    27, // dist along axis = 15
    27, // dist along axis = 16
    26, // dist along axis = 17
    25, // dist along axis = 18
    24, // dist along axis = 19
    24, // dist along axis = 20
    23, // dist along axis = 21
    22, // dist along axis = 22
    21, // dist along axis = 23
    19, // dist along axis = 24
    18, // dist along axis = 25
    17, // dist along axis = 26
    15, // dist along axis = 27
    13, // dist along axis = 28
    10, // dist along axis = 29
    6, // dist along axis = 30
    0, // dist along axis = 31
};

