// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec10[11] = {
    10, // dist along axis = 0
    10, // dist along axis = 1
    10, // dist along axis = 2
    10, // dist along axis = 3
    9, // dist along axis = 4
    9, // dist along axis = 5
    8, // dist along axis = 6
    7, // dist along axis = 7
    6, // dist along axis = 8
    4, // dist along axis = 9
    0, // dist along axis = 10
};

