// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec25[26] = {
    25, // dist along axis = 0
    25, // dist along axis = 1
    25, // dist along axis = 2
    25, // dist along axis = 3
    25, // dist along axis = 4
    24, // dist along axis = 5
    24, // dist along axis = 6
    24, // dist along axis = 7
    24, // dist along axis = 8
    23, // dist along axis = 9
    23, // dist along axis = 10
    22, // dist along axis = 11
    22, // dist along axis = 12
    21, // dist along axis = 13
    21, // dist along axis = 14
    20, // dist along axis = 15
    19, // dist along axis = 16
    18, // dist along axis = 17
    17, // dist along axis = 18
    16, // dist along axis = 19
    15, // dist along axis = 20
    13, // dist along axis = 21
    11, // dist along axis = 22
    9, // dist along axis = 23
    5, // dist along axis = 24
    0, // dist along axis = 25
};

