// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec13[14] = {
    13, // dist along axis = 0
    13, // dist along axis = 1
    13, // dist along axis = 2
    13, // dist along axis = 3
    12, // dist along axis = 4
    12, // dist along axis = 5
    12, // dist along axis = 6
    11, // dist along axis = 7
    10, // dist along axis = 8
    9, // dist along axis = 9
    8, // dist along axis = 10
    7, // dist along axis = 11
    4, // dist along axis = 12
    0, // dist along axis = 13
};

