// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec46[47] = {
    46, // dist along axis = 0
    46, // dist along axis = 1
    46, // dist along axis = 2
    46, // dist along axis = 3
    46, // dist along axis = 4
    46, // dist along axis = 5
    46, // dist along axis = 6
    45, // dist along axis = 7
    45, // dist along axis = 8
    45, // dist along axis = 9
    45, // dist along axis = 10
    45, // dist along axis = 11
    44, // dist along axis = 12
    44, // dist along axis = 13
    44, // dist along axis = 14
    43, // dist along axis = 15
    43, // dist along axis = 16
    43, // dist along axis = 17
    42, // dist along axis = 18
    42, // dist along axis = 19
    41, // dist along axis = 20
    41, // dist along axis = 21
    40, // dist along axis = 22
    40, // dist along axis = 23
    39, // dist along axis = 24
    39, // dist along axis = 25
    38, // dist along axis = 26
    37, // dist along axis = 27
    36, // dist along axis = 28
    36, // dist along axis = 29
    35, // dist along axis = 30
    34, // dist along axis = 31
    33, // dist along axis = 32
    32, // dist along axis = 33
    31, // dist along axis = 34
    30, // dist along axis = 35
    28, // dist along axis = 36
    27, // dist along axis = 37
    26, // dist along axis = 38
    24, // dist along axis = 39
    22, // dist along axis = 40
    20, // dist along axis = 41
    18, // dist along axis = 42
    15, // dist along axis = 43
    12, // dist along axis = 44
    7, // dist along axis = 45
    0, // dist along axis = 46
};

