// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec32[33] = {
    32, // dist along axis = 0
    32, // dist along axis = 1
    32, // dist along axis = 2
    32, // dist along axis = 3
    32, // dist along axis = 4
    32, // dist along axis = 5
    31, // dist along axis = 6
    31, // dist along axis = 7
    31, // dist along axis = 8
    31, // dist along axis = 9
    30, // dist along axis = 10
    30, // dist along axis = 11
    30, // dist along axis = 12
    29, // dist along axis = 13
    29, // dist along axis = 14
    28, // dist along axis = 15
    28, // dist along axis = 16
    27, // dist along axis = 17
    26, // dist along axis = 18
    26, // dist along axis = 19
    25, // dist along axis = 20
    24, // dist along axis = 21
    23, // dist along axis = 22
    22, // dist along axis = 23
    21, // dist along axis = 24
    20, // dist along axis = 25
    18, // dist along axis = 26
    17, // dist along axis = 27
    15, // dist along axis = 28
    13, // dist along axis = 29
    10, // dist along axis = 30
    6, // dist along axis = 31
    0, // dist along axis = 32
};

