// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec30[31] = {
    30, // dist along axis = 0
    30, // dist along axis = 1
    30, // dist along axis = 2
    30, // dist along axis = 3
    30, // dist along axis = 4
    30, // dist along axis = 5
    29, // dist along axis = 6
    29, // dist along axis = 7
    29, // dist along axis = 8
    29, // dist along axis = 9
    28, // dist along axis = 10
    28, // dist along axis = 11
    27, // dist along axis = 12
    27, // dist along axis = 13
    27, // dist along axis = 14
    26, // dist along axis = 15
    25, // dist along axis = 16
    25, // dist along axis = 17
    24, // dist along axis = 18
    23, // dist along axis = 19
    22, // dist along axis = 20
    21, // dist along axis = 21
    20, // dist along axis = 22
    19, // dist along axis = 23
    18, // dist along axis = 24
    16, // dist along axis = 25
    15, // dist along axis = 26
    12, // dist along axis = 27
    10, // dist along axis = 28
    6, // dist along axis = 29
    0, // dist along axis = 30
};

