// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec16[17] = {
    16, // dist along axis = 0
    16, // dist along axis = 1
    16, // dist along axis = 2
    16, // dist along axis = 3
    15, // dist along axis = 4
    15, // dist along axis = 5
    15, // dist along axis = 6
    14, // dist along axis = 7
    14, // dist along axis = 8
    13, // dist along axis = 9
    12, // dist along axis = 10
    12, // dist along axis = 11
    10, // dist along axis = 12
    9, // dist along axis = 13
    7, // dist along axis = 14
    4, // dist along axis = 15
    0, // dist along axis = 16
};

