// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec34[35] = {
    34, // dist along axis = 0
    34, // dist along axis = 1
    34, // dist along axis = 2
    34, // dist along axis = 3
    34, // dist along axis = 4
    34, // dist along axis = 5
    33, // dist along axis = 6
    33, // dist along axis = 7
    33, // dist along axis = 8
    33, // dist along axis = 9
    32, // dist along axis = 10
    32, // dist along axis = 11
    32, // dist along axis = 12
    31, // dist along axis = 13
    31, // dist along axis = 14
    31, // dist along axis = 15
    30, // dist along axis = 16
    29, // dist along axis = 17
    29, // dist along axis = 18
    28, // dist along axis = 19
    27, // dist along axis = 20
    27, // dist along axis = 21
    26, // dist along axis = 22
    25, // dist along axis = 23
    24, // dist along axis = 24
    23, // dist along axis = 25
    22, // dist along axis = 26
    20, // dist along axis = 27
    19, // dist along axis = 28
    17, // dist along axis = 29
    16, // dist along axis = 30
    13, // dist along axis = 31
    10, // dist along axis = 32
    6, // dist along axis = 33
    0, // dist along axis = 34
};

