// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec29[30] = {
    29, // dist along axis = 0
    29, // dist along axis = 1
    29, // dist along axis = 2
    29, // dist along axis = 3
    29, // dist along axis = 4
    29, // dist along axis = 5
    28, // dist along axis = 6
    28, // dist along axis = 7
    28, // dist along axis = 8
    28, // dist along axis = 9
    27, // dist along axis = 10
    27, // dist along axis = 11
    26, // dist along axis = 12
    26, // dist along axis = 13
    25, // dist along axis = 14
    25, // dist along axis = 15
    24, // dist along axis = 16
    23, // dist along axis = 17
    23, // dist along axis = 18
    22, // dist along axis = 19
    21, // dist along axis = 20
    20, // dist along axis = 21
    19, // dist along axis = 22
    17, // dist along axis = 23
    16, // dist along axis = 24
    14, // dist along axis = 25
    12, // dist along axis = 26
    10, // dist along axis = 27
    6, // dist along axis = 28
    0, // dist along axis = 29
};

