// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec45[46] = {
    45, // dist along axis = 0
    45, // dist along axis = 1
    45, // dist along axis = 2
    45, // dist along axis = 3
    45, // dist along axis = 4
    45, // dist along axis = 5
    45, // dist along axis = 6
    44, // dist along axis = 7
    44, // dist along axis = 8
    44, // dist along axis = 9
    44, // dist along axis = 10
    44, // dist along axis = 11
    43, // dist along axis = 12
    43, // dist along axis = 13
    43, // dist along axis = 14
    42, // dist along axis = 15
    42, // dist along axis = 16
    42, // dist along axis = 17
    41, // dist along axis = 18
    41, // dist along axis = 19
    40, // dist along axis = 20
    40, // dist along axis = 21
    39, // dist along axis = 22
    39, // dist along axis = 23
    38, // dist along axis = 24
    37, // dist along axis = 25
    37, // dist along axis = 26
    36, // dist along axis = 27
    35, // dist along axis = 28
    34, // dist along axis = 29
    34, // dist along axis = 30
    33, // dist along axis = 31
    32, // dist along axis = 32
    31, // dist along axis = 33
    29, // dist along axis = 34
    28, // dist along axis = 35
    27, // dist along axis = 36
    25, // dist along axis = 37
    24, // dist along axis = 38
    22, // dist along axis = 39
    20, // dist along axis = 40
    18, // dist along axis = 41
    15, // dist along axis = 42
    12, // dist along axis = 43
    7, // dist along axis = 44
    0, // dist along axis = 45
};

