// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec40[41] = {
    40, // dist along axis = 0
    40, // dist along axis = 1
    40, // dist along axis = 2
    40, // dist along axis = 3
    40, // dist along axis = 4
    40, // dist along axis = 5
    40, // dist along axis = 6
    39, // dist along axis = 7
    39, // dist along axis = 8
    39, // dist along axis = 9
    39, // dist along axis = 10
    38, // dist along axis = 11
    38, // dist along axis = 12
    38, // dist along axis = 13
    37, // dist along axis = 14
    37, // dist along axis = 15
    37, // dist along axis = 16
    36, // dist along axis = 17
    36, // dist along axis = 18
    35, // dist along axis = 19
    35, // dist along axis = 20
    34, // dist along axis = 21
    33, // dist along axis = 22
    33, // dist along axis = 23
    32, // dist along axis = 24
    31, // dist along axis = 25
    30, // dist along axis = 26
    30, // dist along axis = 27
    29, // dist along axis = 28
    28, // dist along axis = 29
    26, // dist along axis = 30
    25, // dist along axis = 31
    24, // dist along axis = 32
    22, // dist along axis = 33
    21, // dist along axis = 34
    19, // dist along axis = 35
    17, // dist along axis = 36
    14, // dist along axis = 37
    11, // dist along axis = 38
    7, // dist along axis = 39
    0, // dist along axis = 40
};

