// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec44[45] = {
    44, // dist along axis = 0
    44, // dist along axis = 1
    44, // dist along axis = 2
    44, // dist along axis = 3
    44, // dist along axis = 4
    44, // dist along axis = 5
    44, // dist along axis = 6
    43, // dist along axis = 7
    43, // dist along axis = 8
    43, // dist along axis = 9
    43, // dist along axis = 10
    43, // dist along axis = 11
    42, // dist along axis = 12
    42, // dist along axis = 13
    42, // dist along axis = 14
    41, // dist along axis = 15
    41, // dist along axis = 16
    41, // dist along axis = 17
    40, // dist along axis = 18
    40, // dist along axis = 19
    39, // dist along axis = 20
    39, // dist along axis = 21
    38, // dist along axis = 22
    38, // dist along axis = 23
    37, // dist along axis = 24
    36, // dist along axis = 25
    35, // dist along axis = 26
    35, // dist along axis = 27
    34, // dist along axis = 28
    33, // dist along axis = 29
    32, // dist along axis = 30
    31, // dist along axis = 31
    30, // dist along axis = 32
    29, // dist along axis = 33
    28, // dist along axis = 34
    26, // dist along axis = 35
    25, // dist along axis = 36
    24, // dist along axis = 37
    22, // dist along axis = 38
    20, // dist along axis = 39
    18, // dist along axis = 40
    15, // dist along axis = 41
    12, // dist along axis = 42
    7, // dist along axis = 43
    0, // dist along axis = 44
};

