// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec33[34] = {
    33, // dist along axis = 0
    33, // dist along axis = 1
    33, // dist along axis = 2
    33, // dist along axis = 3
    33, // dist along axis = 4
    33, // dist along axis = 5
    32, // dist along axis = 6
    32, // dist along axis = 7
    32, // dist along axis = 8
    32, // dist along axis = 9
    31, // dist along axis = 10
    31, // dist along axis = 11
    31, // dist along axis = 12
    30, // dist along axis = 13
    30, // dist along axis = 14
    29, // dist along axis = 15
    29, // dist along axis = 16
    28, // dist along axis = 17
    28, // dist along axis = 18
    27, // dist along axis = 19
    26, // dist along axis = 20
    25, // dist along axis = 21
    25, // dist along axis = 22
    24, // dist along axis = 23
    23, // dist along axis = 24
    21, // dist along axis = 25
    20, // dist along axis = 26
    19, // dist along axis = 27
    17, // dist along axis = 28
    15, // dist along axis = 29
    13, // dist along axis = 30
    10, // dist along axis = 31
    6, // dist along axis = 32
    0, // dist along axis = 33
};

