// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec27[28] = {
    27, // dist along axis = 0
    27, // dist along axis = 1
    27, // dist along axis = 2
    27, // dist along axis = 3
    27, // dist along axis = 4
    27, // dist along axis = 5
    26, // dist along axis = 6
    26, // dist along axis = 7
    26, // dist along axis = 8
    25, // dist along axis = 9
    25, // dist along axis = 10
    25, // dist along axis = 11
    24, // dist along axis = 12
    24, // dist along axis = 13
    23, // dist along axis = 14
    22, // dist along axis = 15
    22, // dist along axis = 16
    21, // dist along axis = 17
    20, // dist along axis = 18
    19, // dist along axis = 19
    18, // dist along axis = 20
    17, // dist along axis = 21
    15, // dist along axis = 22
    14, // dist along axis = 23
    12, // dist along axis = 24
    9, // dist along axis = 25
    6, // dist along axis = 26
    0, // dist along axis = 27
};

