// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec28[29] = {
    28, // dist along axis = 0
    28, // dist along axis = 1
    28, // dist along axis = 2
    28, // dist along axis = 3
    28, // dist along axis = 4
    28, // dist along axis = 5
    27, // dist along axis = 6
    27, // dist along axis = 7
    27, // dist along axis = 8
    27, // dist along axis = 9
    26, // dist along axis = 10
    26, // dist along axis = 11
    25, // dist along axis = 12
    25, // dist along axis = 13
    24, // dist along axis = 14
    24, // dist along axis = 15
    23, // dist along axis = 16
    22, // dist along axis = 17
    21, // dist along axis = 18
    21, // dist along axis = 19
    20, // dist along axis = 20
    18, // dist along axis = 21
    17, // dist along axis = 22
    16, // dist along axis = 23
    14, // dist along axis = 24
    12, // dist along axis = 25
    10, // dist along axis = 26
    6, // dist along axis = 27
    0, // dist along axis = 28
};

