// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec50[51] = {
    50, // dist along axis = 0
    50, // dist along axis = 1
    50, // dist along axis = 2
    50, // dist along axis = 3
    50, // dist along axis = 4
    50, // dist along axis = 5
    50, // dist along axis = 6
    50, // dist along axis = 7
    49, // dist along axis = 8
    49, // dist along axis = 9
    49, // dist along axis = 10
    49, // dist along axis = 11
    49, // dist along axis = 12
    48, // dist along axis = 13
    48, // dist along axis = 14
    48, // dist along axis = 15
    47, // dist along axis = 16
    47, // dist along axis = 17
    47, // dist along axis = 18
    46, // dist along axis = 19
    46, // dist along axis = 20
    45, // dist along axis = 21
    45, // dist along axis = 22
    44, // dist along axis = 23
    44, // dist along axis = 24
    43, // dist along axis = 25
    43, // dist along axis = 26
    42, // dist along axis = 27
    41, // dist along axis = 28
    41, // dist along axis = 29
    40, // dist along axis = 30
    39, // dist along axis = 31
    38, // dist along axis = 32
    38, // dist along axis = 33
    37, // dist along axis = 34
    36, // dist along axis = 35
    35, // dist along axis = 36
    34, // dist along axis = 37
    32, // dist along axis = 38
    31, // dist along axis = 39
    30, // dist along axis = 40
    28, // dist along axis = 41
    27, // dist along axis = 42
    25, // dist along axis = 43
    23, // dist along axis = 44
    21, // dist along axis = 45
    19, // dist along axis = 46
    16, // dist along axis = 47
    13, // dist along axis = 48
    8, // dist along axis = 49
    0, // dist along axis = 50
};

