// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec26[27] = {
    26, // dist along axis = 0
    26, // dist along axis = 1
    26, // dist along axis = 2
    26, // dist along axis = 3
    26, // dist along axis = 4
    26, // dist along axis = 5
    25, // dist along axis = 6
    25, // dist along axis = 7
    25, // dist along axis = 8
    24, // dist along axis = 9
    24, // dist along axis = 10
    24, // dist along axis = 11
    23, // dist along axis = 12
    23, // dist along axis = 13
    22, // dist along axis = 14
    21, // dist along axis = 15
    20, // dist along axis = 16
    20, // dist along axis = 17
    19, // dist along axis = 18
    18, // dist along axis = 19
    16, // dist along axis = 20
    15, // dist along axis = 21
    14, // dist along axis = 22
    12, // dist along axis = 23
    9, // dist along axis = 24
    6, // dist along axis = 25
    0, // dist along axis = 26
};

