// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016
#include "chordVec.h"

const unsigned char chordVec37[38] = {
    37, // dist along axis = 0
    37, // dist along axis = 1
    37, // dist along axis = 2
    37, // dist along axis = 3
    37, // dist along axis = 4
    37, // dist along axis = 5
    37, // dist along axis = 6
    36, // dist along axis = 7
    36, // dist along axis = 8
    36, // dist along axis = 9
    36, // dist along axis = 10
    35, // dist along axis = 11
    35, // dist along axis = 12
    35, // dist along axis = 13
    34, // dist along axis = 14
    34, // dist along axis = 15
    33, // dist along axis = 16
    33, // dist along axis = 17
    32, // dist along axis = 18
    32, // dist along axis = 19
    31, // dist along axis = 20
    30, // dist along axis = 21
    30, // dist along axis = 22
    29, // dist along axis = 23
    28, // dist along axis = 24
    27, // dist along axis = 25
    26, // dist along axis = 26
    25, // dist along axis = 27
    24, // dist along axis = 28
    23, // dist along axis = 29
    21, // dist along axis = 30
    20, // dist along axis = 31
    18, // dist along axis = 32
    16, // dist along axis = 33
    14, // dist along axis = 34
    11, // dist along axis = 35
    7, // dist along axis = 36
    0, // dist along axis = 37
};

