
///////////////////////////////////////////
// build table chordVec[d] of circle 1/2 widths at distances d from center
// Code adapted from RobG's EduKit
// Uses Bresenham's circle algorithm
// Modified from RobG's EduKit by Eric Freudenthal and David Pruitt 2016
///////////////////////////////////////////
void computeChordVec(unsigned char chordVec[], unsigned char radius) 
{
  int col = radius, row = 0;	/* first coordinate (radius, 0) */
  
  // key insight: (col+1)**2 - col**2 = 2col+1
  
  int dColSquared = 2 * col - 1;  // change in col**2 for a unit decrease in col
  int dRowSquared = 1;	    // change in row**2 for a unit increase in row

  int radiusSqErr = 0;		/* (radius, 0) is on the circle  */
  int colPrev = 0;		/* initially bogus value  to force first entry*/
  while (col >= row) {		/* only sweep first octant */
    chordVec[row] = col;      /* row always changes in first octant */

    /* mirror into 2nd octant */
    if (colPrev != col)		/* col sometimes repeats in first octant */
      chordVec[col] = row;	/* only save first (max) col for row */
    colPrev = col;

    row++;			/* move vertically (slope <= -1 for first octant) */
    radiusSqErr += dRowSquared;	/* current radiusSqErr */
    dRowSquared += 2; 		/* next dRowSquared */
    if ((2 * radiusSqErr) > dColSquared) { /* only update col if error reduced */
      col--;			/* move horizontally */
      radiusSqErr -= dColSquared;	/* current radiusSqErr */
      dColSquared -= 2;	      /* next dColSquared */
    }
  }
}

#include "stdio.h"
#include "assert.h"


// Generate circles as source files
// (c) Eric Freudenthal, 2016
int main()
{
  int radius;
  char chordVec[151];
  FILE *includeFile = fopen("circles.h", "w");
  assert(includeFile);
  fprintf(includeFile, "// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016\n");
  fprintf(includeFile, "#ifndef chordVecs_included\n#define chordVecs_included\n\n");
  for (radius = 2; radius <= 150; radius++) {
    char filename[100];
    unsigned char chordIndex;
    
    computeChordVec(chordVec, radius);
    
    fprintf(includeFile, "extern const AbCircle circle%d;\n", radius);
    
    sprintf(filename, "circle%d.c", radius);
    FILE *circleFile = fopen(filename, "w");
    assert(circleFile);
    
    fprintf(circleFile, "// Automatically generated by makeCircles.  (c) Eric Freudenthal, 2016\n");
    fprintf(circleFile, "#include \"../_abCircle.h\"\n\n");
    fprintf(circleFile, "static const unsigned char chordVec%d[%d] = {\n", radius, radius+1);
    for (chordIndex = 0; chordIndex <= radius; chordIndex ++) 
      fprintf(circleFile, "    %d, // dist along axis = %d\n", chordVec[chordIndex], chordIndex);
    fprintf(circleFile, "};\n\n");

    fprintf(circleFile, "const AbCircle circle%d = {" , radius);
    fprintf(circleFile, "  abCircleGetBounds, abCircleCheck, chordVec%d, %d", radius, radius);
    fprintf(circleFile, "};\n");
    fclose(circleFile);
  }
  fprintf(includeFile, "\n#endif // included \n");
  fclose(includeFile);
}



    
    
    

